   # - name: change hostname
   #   shell: hostname {{IM_MASTER_FQDN}}-vpn

    - stat:
        path: /etc/openvpn/easy-rsa/2.0/keys/dh2048.pem
      register: dhcert

    - name: Include Certificate Generation tasks
      include_tasks: "cert.yml"
      when: not dhcert.stat.exists

    - name: Create the file of server configuration
      template: src=server.j2 dest=/etc/openvpn/server.conf mode="0644" owner=root group=root

    - name: execute the vpn server
      command: openvpn --config server.conf --daemon chdir=/etc/openvpn/ creates=/etc/openvpn/openvpn-status.log
