---
    - name: Include "{{ansible_os_family}}" OpenVPN tasks
      include_tasks: "{{ansible_os_family}}.yaml"

    - name: Include "{{openvpn_type_of_node}}" OpenVPN recipe
      include_tasks: "{{openvpn_type_of_node}}.yaml"
