---
    - name: Include "{{ansible_os_family}}" OpenVPN tasks
      include: "{{ansible_os_family}}.yaml"

    - name: Include "{{openvpn_type_of_node}}" mesos recipe
      include: "{{openvpn_type_of_node}}.yaml"
